export const BRAND = {
  background: "#f6f1e8",
  foreground: "#201a15",
  primary: "#9b7a43",
  primaryHover: "#816437",
  accent: "#c4a269",
  surface: "#fffaf1",
  border: "#e8dcc7",
  muted: "#6f6254",
  subtleText: "#998c7d",
  overlaySoft: "rgba(246,241,232,0.88)",
  success: "#22c55e",
  error: "#ef4444",
  radiusXl: "0.75rem",
  shadowCard: "0 10px 40px 0 rgba(62, 48, 30, 0.08)",
} as const;

export const BRAND_CSS_VARIABLES = {
  "--background": BRAND.background,
  "--foreground": BRAND.foreground,
  "--color-primary": BRAND.primary,
  "--color-primary-hover": BRAND.primaryHover,
  "--color-accent": BRAND.accent,
  "--color-surface": BRAND.surface,
  "--color-border": BRAND.border,
  "--color-muted": BRAND.muted,
  "--color-text-strong": BRAND.foreground,
  "--radius-xl": BRAND.radiusXl,
  "--shadow-card": BRAND.shadowCard,
} as const;
